from abc import ABC, abstractmethod
from bs4 import BeautifulSoup
import requests
from requests import Response


class Scraper(ABC):
    """ Base class for website scrapers."""

    @abstractmethod
    def __init__(self):
        pass


class AEMScraper(Scraper):

    def __init__(self, aem_path: str, audience_role: str) -> None:
        """ Web scraper for Adobe Experience Manager website.

        :param aem_path: Path generated by Adobe Experience Manager. Example: /content/us/en/foo-bar
        :type aem_path: str
        :param audience_role: Url parameter value for audience role. Can be IndividualInvestor, FinancialProfessional, or Institutional
        :type audience_role: str
        """

        super().__init__()
        self.base_url = 'https://www.invesco.com'
        self.aem_path = aem_path
        self.audience_role = audience_role
        self.full_path = self.create_full_url()
        self.publish_date = None
        self.status_code = None

    def create_full_url(self) -> str:
        """Creates full url path from AEM path.

        :return: HTTPS path of the AEM webpage constructed by formatting the AEM path property
        :rtype: str
        """

        full_path = self.aem_path.replace(r'/content/invesco', self.base_url) + '.html'
        return full_path

    @property
    def url_with_audience_role(self) -> str:
        """Creates a property for the full url with the audience role parameter included.

        :return: Full url with audience role parameter included
        :rtype: str
        """

        return self.full_path + '?audienceRole=' + self.audience_role

    def get_html(self) -> Response|None:
        """Makes http get request to an AEM webpage.

        :return: Response object or None
        :rtype: requests.Response | None
        """

        params = {'audienceRole': self.audience_role}
        response = requests.get(self.full_path, params=params)
        self.status_code = response.status_code
        # Ensure status code is 200
        if response.status_code != 200:
            return None
        return response

    @staticmethod
    def get_lxml_from_response(response_object: Response) -> BeautifulSoup:
        """ Parses response object using Beautiful Soup's lxml parser.

        :param response_object: Response object generated by requests package
        :type response_object: requests.Response
        :return: Beautiful Soup object parsed with lxml
        :rtype: BeautifulSoup
        """

        content = response_object.content
        return BeautifulSoup(content, 'lxml')


# Scraper to be used for each instance of an AEM page - insights pages only
class InsightPageScraper(AEMScraper):

    def __init__(self, aem_path: str, audience_role: str):
        super(InsightPageScraper, self).__init__(aem_path, audience_role)

    @staticmethod
    def parse_publish_date(soup: BeautifulSoup) -> str:
        publish_date_element = soup.find('span', attrs={'class': 'article-hero__date'})
        if not publish_date_element:
            raise AttributeError
        publish_date: str = publish_date_element['data-publishdate']
        return publish_date

    def scrape(self):
        response = self.get_html()
        if not response:
            return
        soup = self.get_lxml_from_response(response)
        # Save publish date
        try:
            publish_date = self.parse_publish_date(soup)
        except AttributeError:
            print('Publish date parameter does not exist for:')
            print(self.url_with_audience_role)
        else:
            self.publish_date = publish_date
